context("vos_start")

expect_error(vos_status(NA))
#             "No virtuoso process found")
